### ISSUE TITLE
copyright question

### ISSUE THREAD

**Issue by cryptozeny** [cryply/crp_yespower_1_0_python3#1]
hi cryply devs,

thanks for great code. i modified some lines and added our copyright here. is it ok? if it could be a problem i will remove it. :)

https://github.com/bitzenyPlus/zny_yespower_python/blob/a585989f5e577519084848c96518ab43f446027c/yespower.c#L3

**Comment by cryply** [comment]
Hey Cryptozeny.

Its perfectly fine with us.
